name: Release RAML to OpenAPI Converter

on:
  workflow_dispatch:
    inputs:
      ballerina_version:
        description: Ballerina Version
        required: true
        default: "2201.13.0"

jobs:
  publish-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21.0.3

      - name: Set up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: ${{ github.event.inputs.ballerina_version }}

      - name: Set version env variable
        run: |
          VERSION=$(grep -w 'version' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev | xargs)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Update version
        run: sed -i 's/^version=\(.*\)-SNAPSHOT$/version=\1/' gradle.properties

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build

      - name: Pre release dependency version update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Version: ${VERSION}"
          git config user.name ${{ github.actor }}
          git config user.email ${{ secrets.USER_EMAIL }}
          git checkout -b release-${VERSION}
          git add gradle.properties
          git commit -m "Move dependencies to stable version" || echo "No changes to commit"

      - name: Publish artifact
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          packagePublishRepo: ${{ github.repository }}
        run: |
          git stash
          ./gradlew release -Prelease.useAutomaticVersion=true
          ./gradlew -Pversion=${VERSION} publish -x test
      - name: Create Github release from the release tag
        run: |
          curl --request POST 'https://api.github.com/repos/${{ github.repository }}/releases' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
             "tag_name": "v'"$VERSION"'",
             "name": "raml-to-openapi-converter-v'"$VERSION"'"
          }'
